apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
spec:
  replicas: 3  # 允许扩展
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: zeshuli/data_processor:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_USER
          value: "admin"
        - name: RABBITMQ_PASS
          value: "password123"
        - name: INPUT_QUEUE
          value: "preprocessing_queue"