apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: queue  # 端口 5672（消息队列）
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management  # 端口 15672（管理界面）
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP